---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен соответсвовать требованиям SPA приложения, не перезагружая страницу при перемещении между разделами
  - Все ссылки на сайте должны быть рабочими и кликабельными
  - Сайт должен корректно отображаться при смене языка
  - Корзина должна храниться в сессии браузера
  

