---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары. #чек-боксы, список
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге. #купить здесь и сейчас
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. #скорость соединения, минификация файлов, оптимизация загрузки, кеширование файлов 
  - Сайт должен быть безопасным и защищать данные пользователя. #Протокол HTTPS, ответы от сервера
  - Сайт должен иметь мобильную версию. #адаптивность
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров. #кроссбрайзерность
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах. #адаптивность 
  - SPA приложение, которое не перезагружает страницу #проверка одностраничного приложения
  - Корзина хранится в сессии браузера. #куки
implicit:
  - Валюта указана в соответствии с выбранным языком. Русский - в рублях. Английский - в долларах.
  - Наличие изображения (превью) для каждого товара.
  - Изображения единого стандарта (размер, разрешение и пропорций). #оптимизация изображений
  - Название товаров по единому шаблону (категория товара, бренд, модель, опциональные параметры).
  - Фильтровать товары по нескольким значениям одновременно (название, категория, цена)
  - Выбор категории товаров позволяет задать пустое значение для просмотра всех товаров.
  - Показывать количество результатов поиска.
  - Показывать количество страниц по результатам поиска.
  - Возможность увеличить изображение при наведении. 
  - Оповещение при добавлении товара в корзину.
  - На иконке корзины отображается количество добавленных товаров.
  - Товар удаляется без перезагрузки страницы
  - Удаление товара происходит с подтверждением
  - Заказ товара происходит с подтверждением
  - Просмотр заказов
  - Статус заказа (принят, в пути, отменен)
  - Присвоение уникального номера заказу
  - Цены без десятичных.
  - Неактивные кнопки должны быть серыми и некликабельными.
  - Нет битых ссылок и картинок.
  - Текст интерфейса соответствуют выбранному языку (меню, шапка, описание товара, категории и кнопки).
  - При отсутствии интернета, пользователь видит страницу с сообщением об отсутствии интернет-соединения.
  - Указывать доступное количество товара на странице товара и в корзине.
  - Сайт должен корректно отображаться на всех языках. #мультиязычность. 

